/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Window1.java
 *
 * Created on 28/12/2011, 15:54:18
 */
package Presentation;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.SpinnerListModel;

/**
 *
 * @author clara
 */
public class Window1 extends javax.swing.JFrame implements com.imagine.component.calendar.DateListener {

    private ReservarHabitacioView viewController;
    /** Creates new form Window1 */
    public Window1(ReservarHabitacioView controller) {
        this.viewController = controller;
        initComponents();
    }
    
    /**
     * Carrega la llista de poblacions del sistema
     * @param poblacions 
     */
    public void loadPoblacions(List<String> poblacions) {
        //Actualitza la llista d'elements a mostra per les poblacions del sistema
        String[] list = new String[poblacions.size()];
        int i = 0;
        for(String poblacio : poblacions){
            list[i] = poblacio;
            i++;
        }
        poblacioComboBox.setModel(new javax.swing.DefaultComboBoxModel(list));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        poblacioLabel = new javax.swing.JLabel();
        dIniLabel = new javax.swing.JLabel();
        poblacioComboBox = new javax.swing.JComboBox();
        dIniCalendar = new com.imagine.component.calendar.CalendarComponent();
        dFiLabel = new javax.swing.JLabel();
        dFiCalendar = new com.imagine.component.calendar.CalendarComponent();
        numocLabel = new javax.swing.JLabel();
        messageArea = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        numOcSpinner = new javax.swing.JSpinner();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        poblacioLabel.setText("Població");

        dIniLabel.setText("Data d'inici");

        poblacioComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dIniCalendar.addDateListener(this);

        dFiLabel.setText("Data de finalització");

        numocLabel.setText("Número d'ocupants");

        messageArea.setText(" ");
        messageArea.setForeground(Color.red);

        confirmButton.setText("D'acord");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel·la");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        Integer[] values = {1,2,3,4,5,6,7,8,9};
        numOcSpinner.setModel(new SpinnerListModel(values));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(dIniLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 158, Short.MAX_VALUE)
                        .add(dIniCalendar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(poblacioLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 180, Short.MAX_VALUE)
                        .add(poblacioComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 223, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(dFiLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 107, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(numOcSpinner)
                            .add(dFiCalendar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, Short.MAX_VALUE))))
                .add(156, 156, 156))
            .add(layout.createSequentialGroup()
                .add(85, 85, 85)
                .add(confirmButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 160, Short.MAX_VALUE)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(147, 147, 147))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(numocLabel)
                .addContainerGap(489, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(messageArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(poblacioLabel)
                    .add(poblacioComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dIniLabel)
                    .add(dIniCalendar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dFiLabel)
                    .add(dFiCalendar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(numocLabel))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(numOcSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(22, 22, 22)
                .add(messageArea)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(confirmButton)
                    .add(cancelButton))
                .add(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Tractar quan es prem el botó confirmar
     * @param evt 
     */
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        viewController.confirmacioWindow1(poblacioComboBox.getSelectedItem().toString(), 
                dIniCalendar.getDate(), dFiCalendar.getDate(), 
                Integer.valueOf(numOcSpinner.getValue().toString()));
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * Tractar quan es prem el botó cancel·lar
     * @param evt 
     * @author clara
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // Tanca l'aplicació
        viewController.tanca();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private com.imagine.component.calendar.CalendarComponent dFiCalendar;
    private javax.swing.JLabel dFiLabel;
    private com.imagine.component.calendar.CalendarComponent dIniCalendar;
    private javax.swing.JLabel dIniLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel messageArea;
    private javax.swing.JSpinner numOcSpinner;
    private javax.swing.JLabel numocLabel;
    private javax.swing.JComboBox poblacioComboBox;
    private javax.swing.JLabel poblacioLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void dateChanged(Date date) {
        Calendar c = Calendar.getInstance();
        c.setTime(date);
        c.add(Calendar.DATE, 1);
        Date newDate = c.getTime();
        dFiCalendar.setDate(newDate);
    }

    public void mostraMissatge(String missatge) {
        messageArea.setText(missatge);
    }
}
