/*
 * Window3.java
 *
 * Created on 28-dic-2011, 16:39:03
 */
package Presentation;

import TupleTypes.DadesReserva;
import java.text.SimpleDateFormat;

/**
 *
 * @author elena i clara
 */
public class Window3 extends javax.swing.JFrame {
    
    private ReservarHabitacioView viewController;
    /** Creates new form Window3 */
    public Window3(ReservarHabitacioView viewController) {
        this.viewController = viewController;
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();
    }
    
    
    public void mostraError(String m){
        messageAreaLabel.setText(m);
    }
    
    /*public void mostraPreu(float preu){
        Tpreu.setText(Float.toString(preu));
    }*/
    
    public void mostraDades(DadesReserva r){
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        poblacioValueLabel.setText(r.pob);
        dIniValueLabel.setText(s.format(r.dIni));
        dFiValueLabel.setText(s.format(r.dFi));
        numOcValueLabel.setText(r.numOc.toString());
        hotelValueLabel.setText(r.nomHotel);
        habitacioValueLabel.setText(r.nomTipusHab);
        preuValueLabel.setText(r.preuTotal.toString());
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poblacio = new javax.swing.JLabel();
        dIniLabel = new javax.swing.JLabel();
        dFILabel = new javax.swing.JLabel();
        numOcLabel = new javax.swing.JLabel();
        hotelLabel = new javax.swing.JLabel();
        habitacioLabel = new javax.swing.JLabel();
        preuTotalLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        dniValueTextField = new javax.swing.JTextField();
        dacord = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        messageAreaLabel = new javax.swing.JLabel();
        poblacioValueLabel = new javax.swing.JLabel();
        dIniValueLabel = new javax.swing.JLabel();
        dFiValueLabel = new javax.swing.JLabel();
        numOcValueLabel = new javax.swing.JLabel();
        hotelValueLabel = new javax.swing.JLabel();
        habitacioValueLabel = new javax.swing.JLabel();
        preuValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        poblacio.setText("Població");

        dIniLabel.setText("Data d'inici");

        dFILabel.setText("Data de finalització");

        numOcLabel.setText("Número d'ocupants");

        hotelLabel.setText("Hotel");

        habitacioLabel.setText("Habitació");

        preuTotalLabel.setText("Preu total");

        dniLabel.setText("DNI");

        dacord.setText("D'acord");
        dacord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dacordActionPerformed(evt);
            }
        });

        cancela.setText("Cancel·la");
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        messageAreaLabel.setText(" ");

        poblacioValueLabel.setText("poblacioValueLabel");

        dIniValueLabel.setText("dIniValueLabel");

        dFiValueLabel.setText("dFiValueLabel");

        numOcValueLabel.setText("numOcValueLabel");

        hotelValueLabel.setText("hotelValueLabel");

        habitacioValueLabel.setText("habitacioValueLabel");

        preuValueLabel.setText("preuValueLabel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(98, 98, 98)
                        .add(dacord, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(108, 108, 108)
                        .add(cancela, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(70, 70, 70)
                        .add(messageAreaLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 442, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dniLabel)
                            .add(poblacio)
                            .add(dIniLabel)
                            .add(dFILabel)
                            .add(numOcLabel)
                            .add(hotelLabel)
                            .add(habitacioLabel)
                            .add(preuTotalLabel))
                        .add(48, 48, 48)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(preuValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .add(habitacioValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .add(hotelValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .add(numOcValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .add(dFiValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .add(poblacioValueLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dniValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dIniValueLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))))
                .add(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(poblacio)
                    .add(poblacioValueLabel))
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dIniLabel)
                    .add(dIniValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dFILabel)
                    .add(dFiValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(numOcLabel)
                    .add(numOcValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hotelLabel)
                    .add(hotelValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(habitacioLabel)
                    .add(habitacioValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(preuTotalLabel)
                    .add(preuValueLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 51, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniLabel)
                    .add(dniValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(messageAreaLabel)
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dacord)
                    .add(cancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        // TODO add your handling code here:
         viewController.tanca();
    }//GEN-LAST:event_cancelaActionPerformed

    private void dacordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dacordActionPerformed
        // TODO add your handling code here:
        String dni = this.dniValueTextField.getText().toString();
        if(dni.length() > 0){
            viewController.confirmacioWindow3(dni);
        }
        else mostraError("DNI incorrecte");
    }//GEN-LAST:event_dacordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancela;
    private javax.swing.JLabel dFILabel;
    private javax.swing.JLabel dFiValueLabel;
    private javax.swing.JLabel dIniLabel;
    private javax.swing.JLabel dIniValueLabel;
    private javax.swing.JButton dacord;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniValueTextField;
    private javax.swing.JLabel habitacioLabel;
    private javax.swing.JLabel habitacioValueLabel;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JLabel hotelValueLabel;
    private javax.swing.JLabel messageAreaLabel;
    private javax.swing.JLabel numOcLabel;
    private javax.swing.JLabel numOcValueLabel;
    private javax.swing.JLabel poblacio;
    private javax.swing.JLabel poblacioValueLabel;
    private javax.swing.JLabel preuTotalLabel;
    private javax.swing.JLabel preuValueLabel;
    // End of variables declaration//GEN-END:variables
}
