/*
 * Window3.java
 *
 * Created on 28-dic-2011, 16:39:03
 */
package Presentation;

import TupleTypes.DadesReserva;
import java.text.SimpleDateFormat;

/**
 *
 * @author elena i clara
 */
public class Window3 extends javax.swing.JFrame {
    
    private ReservarHabitacioView viewController;
    /** Creates new form Window3 */
    public Window3() {
        initComponents();
    }
    
    
    public void mostraError(String m){
        Terror.setText(m);
    }
    
    /*public void mostraPreu(float preu){
        Tpreu.setText(Float.toString(preu));
    }*/
    
    public void mostraDades(DadesReserva r){
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        Tpoblacio.setText(r.pob);
        TdIni.setText(s.format(r.dIni));
        TdFi.setText(s.format(r.dFi));
        TnOcup.setText(r.numOc.toString());
        Thotel.setText(r.nomHotel);
        Thabitacio.setText(r.nomTipusHab);
        
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poblacio = new javax.swing.JLabel();
        dIniLabel = new javax.swing.JLabel();
        dFILabel = new javax.swing.JLabel();
        numOcLabel = new javax.swing.JLabel();
        hotelLabel = new javax.swing.JLabel();
        habitacioLabel = new javax.swing.JLabel();
        preuTotalLabel = new javax.swing.JLabel();
        dniLabel = new javax.swing.JLabel();
        dniValueTextField = new javax.swing.JTextField();
        dacord = new javax.swing.JButton();
        cancela = new javax.swing.JButton();
        Tpoblacio = new javax.swing.JTextField();
        TdIni = new javax.swing.JTextField();
        TdFi = new javax.swing.JTextField();
        TnOcup = new javax.swing.JTextField();
        Thotel = new javax.swing.JTextField();
        Thabitacio = new javax.swing.JTextField();
        Tpreu = new javax.swing.JTextField();
        Terror = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        poblacio.setText("Població");

        dIniLabel.setText("Data d'inici");

        dFILabel.setText("Data de finalització");

        numOcLabel.setText("Número d'ocupants");

        hotelLabel.setText("Hotel");

        habitacioLabel.setText("Habitació");

        preuTotalLabel.setText("Preu total");

        dniLabel.setText("DNI");

        dniValueTextField.setText("jTextField8");

        dacord.setText("D'acord");
        dacord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dacordActionPerformed(evt);
            }
        });

        cancela.setText("Cancel·la");
        cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaActionPerformed(evt);
            }
        });

        Tpoblacio.setText("jTextField1");

        TdIni.setText("jTextField2");
        TdIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TdIniActionPerformed(evt);
            }
        });

        TdFi.setText("jTextField3");

        TnOcup.setText("jTextField4");

        Thotel.setText("jTextField5");

        Thabitacio.setText("jTextField6");

        Tpreu.setText("jTextField7");

        Terror.setText("jTextField8");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Terror, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(numOcLabel)
                            .add(hotelLabel)
                            .add(poblacio)
                            .add(dIniLabel)
                            .add(dFILabel)
                            .add(habitacioLabel)
                            .add(preuTotalLabel)
                            .add(dniLabel))
                        .add(48, 48, 48)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(Tpoblacio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(TdIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(TdFi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(TnOcup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Thotel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Thabitacio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(Tpreu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dniValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(dacord)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 322, Short.MAX_VALUE)
                        .add(cancela)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(poblacio)
                    .add(Tpoblacio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TdIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dIniLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TdFi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dFILabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(TnOcup, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(numOcLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Thotel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(hotelLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Thabitacio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(habitacioLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Tpreu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(preuTotalLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dniLabel)
                    .add(dniValueTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(Terror, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dacord)
                    .add(cancela))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TdIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TdIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TdIniActionPerformed

    private void cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaActionPerformed
        // TODO add your handling code here:
         viewController.tanca();
    }//GEN-LAST:event_cancelaActionPerformed

    private void dacordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dacordActionPerformed
        // TODO add your handling code here:
        String dni = this.dniValueTextField.getText();
        if(dni.length() > 0){
            viewController.confirmacioWindow3(dni);
        }
        else mostraError("DNI incorrecte");
    }//GEN-LAST:event_dacordActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TdFi;
    private javax.swing.JTextField TdIni;
    private javax.swing.JTextField Terror;
    private javax.swing.JTextField Thabitacio;
    private javax.swing.JTextField Thotel;
    private javax.swing.JTextField TnOcup;
    private javax.swing.JTextField Tpoblacio;
    private javax.swing.JTextField Tpreu;
    private javax.swing.JButton cancela;
    private javax.swing.JLabel dFILabel;
    private javax.swing.JLabel dIniLabel;
    private javax.swing.JButton dacord;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniValueTextField;
    private javax.swing.JLabel habitacioLabel;
    private javax.swing.JLabel hotelLabel;
    private javax.swing.JLabel numOcLabel;
    private javax.swing.JLabel poblacio;
    private javax.swing.JLabel preuTotalLabel;
    // End of variables declaration//GEN-END:variables
}
